# Generated by Django 3.0 on 2019-12-10 18:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('csnetinventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='acquired',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 18, 13, 49, 647982, tzinfo=utc), verbose_name='date acquired'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='barcode',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='brand',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='m_type',
            field=models.CharField(default='', max_length=200, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='qr',
            field=models.CharField(default='', max_length=200, verbose_name='qr code'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='room',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='serial',
            field=models.CharField(default='', max_length=200, verbose_name='serial number'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(default='DEFAULT NAME', max_length=200),
        ),
    ]
