# Generated by Django 3.0 on 2019-12-10 18:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('csnetinventory', '0003_auto_20191210_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='acquired',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 18, 14, 41, 851846, tzinfo=utc), verbose_name='date acquired'),
        ),
    ]
