# Generated by Django 3.0 on 2019-12-10 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csnetinventory', '0004_auto_20191210_1314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryItem',
        ),
    ]
