# Generated by Django 3.0 on 2019-12-10 18:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('csnetinventory', '0005_delete_inventoryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT NAME', max_length=200)),
                ('barcode', models.IntegerField(default=-1)),
                ('qr', models.CharField(default='', max_length=200, verbose_name='qr code')),
                ('m_type', models.CharField(default='', max_length=200, verbose_name='type')),
                ('serial', models.CharField(default='', max_length=200, verbose_name='serial number')),
                ('room', models.CharField(default='', max_length=200)),
                ('brand', models.CharField(default='', max_length=200)),
                ('acquired', models.DateField(default=datetime.datetime(2019, 12, 10, 18, 17, 23, 450534, tzinfo=utc), verbose_name='date acquired')),
            ],
        ),
    ]
